spring.datasource.url=jdbc:postgresql://dpg-d8egshernols73a9h87g-a/musicdb_9ytm
spring.datasource.username=musicdb_9ytm_user
spring.datasource.password=eWRntYVvvl1MYj5O8EZLTeVGZvs6idZh
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.port=${PORT:8080}
